services:
  mongodb_container:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=admin
    ports:
      - "27017:27017"
    command: mongod
