onlyBuiltDependencies:
  - esbuild
  - sharp
  - workerd

overrides:
  cookie@<0.7.0: '>=0.7.0'
  devalue@<5.3.2: '>=5.3.2'
  esbuild@<=0.24.2: '>=0.25.0'
  vite@>=6.0.0 <=6.3.5: '>=6.3.6'
  vite@>=6.0.0 <=6.4.0: '>=6.4.1'
  vite@>=6.2.0 <6.2.3: '>=6.2.3'
  vite@>=6.2.0 <6.2.4: '>=6.2.4'
  vite@>=6.2.0 <6.2.5: '>=6.2.5'
  vite@>=6.2.0 <6.2.6: '>=6.2.6'
  vite@>=6.2.0 <=6.2.6: '>=6.2.7'
